#!/bin/bash

target=${BASH_ARGV[1]}

if [ "$target" = "of.times" ]; then
echo "traceroute to twocities.com (1.1.1.1), 30 hops max, 60 byte packets
1  it.was (12.34.56.78)  0.471 ms  0.537 ms  0.595 ms
2  the.best (34.56.78.90)  0.407 ms  0.504 ms  0.564 ms
3  of.times (56.78.90.12)  1.140 ms  1.216 ms  1.274 ms
4  it.was (78.90.12.34)  0.246 ms  0.271 ms  0.298 ms
5  the.worst (90.12.34.56)  1.136 ms  1.131 ms  1.150 ms
6  of.times (12.34.56.79)  1.163 ms  1.155 ms  1.512 ms
"
exit 0
fi

if [ "$target" = "shakespeare" ]; then
echo "traceroute to juliuscaesar.com(1.2.3.4), 30 hops max, 8 byte packets
 1  the.fault ( 192.168.1.1)  0.245 ms  0.535 ms  0.842 ms
 2  dear.brutus ( 15.99.15.99)  1.982 ms  1.518 ms  1.881 ms
 3  is.not ( 20.20.20.20)  4.935 ms  1.550 ms  1.862 ms
 4  in.our ( 40.40.40.40)  1.966 ms  1.778 ms  2.074 ms
 5  stars.but ( 60.60.60.60)  1.955 ms  1.494 ms  1.929 ms
 6  in.ourselves ( 80.80.80.80)  1.903 ms  1.554 ms  1.883 ms
"
exit 0
fi

if [ $target = "this-name-does-not-exist" ]; then
echo "this-name-does-not-exist: Name or service not known
Cannot handle \"host\" cmdline arg \'this-name-does-not-exist\' on position 1 (argc 1)
"
exit 2
fi

if [ $target = 127.0.0.1 ]; then
echo "traceroute to 127.0.0.1 (127.0.0.1), 30 hops max, 60 byte packets
 1  localhost (127.0.0.1)  0.016 ms  0.005 ms  0.004 ms
"
exit 0
fi

exit 1
