#!/bin/sh

if [ "$1" == get ] && [ "$2" == --drv_info ]; then
echo "== fw_version  ========================================"
echo "version_moca : 2  ( 0x2 )"
echo "version_major: 10  ( 0xa )"
echo "version_minor: 4  ( 0x4 )"
echo "version_patch: 6  ( 0x6 )"
echo"== end fw_version  ===================================="
fi

exit 0
