#!/bin/sh

if [ "$1" == get ] && [ "$2" == --node_status ]; then
echo '== node_status  ======================================= '
echo 'vendor_id            : 32  ( 0x20 )'
echo 'moca_hw_version      : 856760322  ( 0x33112002 )'
echo 'moca_sw_version_major: 5  ( 0x5 )'
echo 'moca_sw_version_minor: 6  ( 0x6 )'
echo 'moca_sw_version_rev  : 789  ( 0x315 )'
echo 'self_moca_version    : 16  ( 0x10 )'
echo 'qam_256_support      : 0  ( 0x0 )'
echo '== end node_status  =================================== '
fi

if [ "$1" == get ] && [ "$2" == --network_status ]; then
echo '== network_status  ==================================== '
echo 'network_moca_version: 16  ( 0x10 )'
echo 'connected_nodes     : 0  (bitmask 0x0)'
echo 'node_id             : 2  ( 0x2 )'
echo 'nc_node_id          : 1  ( 0x1 )'
echo 'backup_nc_id        : 2  ( 0x2 )'
echo 'bw_status           : 0  ( 0x0 )'
echo 'nodes_usable_bitmask: 0  ( 0x0 )'
echo 'network_taboo_mask  : 0  ( 0x0 )'
echo 'network_taboo_start : 0  ( 0x0 )'
echo '== end network_status  ================================ '
fi

if [ "$1" == get ] && [ "$2" == --privacy_en ]; then
echo 'privacy_en: 1  ( 0x1 )'
fi

if [ "$1" == get ] && [ "$2" == --max_pkt_aggr ]; then
echo 'max_pkt_aggr: 7  ( 0x7 )'
fi

if [ "$1" == get ] && [ "$2" == --preferred_nc ]; then
echo "preferred_nc: 1  ( 0x1 )"
fi

exit 0
