#!/usr/bin/python
#
# Copyright 2011 Google Inc. All Rights Reserved.

"""Code Generator for XML access classes for CWMP DeviceModel objects.

Generates classes to parse and emit XML for objects defined using tr-106
device models.

DeviceModel files expected to be passed to be passed to this code generator
include:
http://www.broadband-forum.org/cwmp/tr-098-1-0-0.xml
http://www.broadband-forum.org/cwmp/tr-098-1-1-0.xml
http://www.broadband-forum.org/cwmp/tr-098-1-2-0.xml
http://www.broadband-forum.org/cwmp/tr-181-2-0-1.xml
http://www.broadband-forum.org/cwmp/tr-181-2-1-0.xml
http://www.broadband-forum.org/cwmp/tr-181-2-2-0.xml

This code generator itself relies on code generated for cwmp-datamodel-1-3.xsd
by generateDS. Its code generation all the way down.
"""

__author__ = 'dgentry@google.com (Denton Gentry)'

import cwmp_datamodel_1_3 as dm
import optparse
import string
import sys
import xml.etree.ElementTree as etree

def EmitPrologue(out):
  """Emit the first few lines of a Python source file.

  Args:
    out - list of strings to collect for output
  """
  out.append("#!/usr/bin/python\n")
  out.append("#\n# THIS FILE IS GENERATED BY " + sys.argv[0] + "\n")
  out.append("# DO NOT MAKE CHANGES HERE, THEY WILL BE OVERWRITTEN.\n\n")
  out.append("\"\"\"Classes to parse and emit XML for DeviceModel objects "
             "defined in CWMP specs.\n\"\"\"\n\n")


def XmlNameMangle(XMLname):
  """Convert an XML object name to a suitable Python class name.

  Examples:
    Device.Routing.RIP. returns Device_Routing_RIP_
    Device.Ethernet.Link.{i}.Stats. returns Device_Ethernet_Link_0i0_Stats_

  Args:
    XMLname - the object name taken directly from the XML file.

  Returns:
    A suitable Python class name.
  """
  tab = string.maketrans(".{}", "_00")
  return string.translate(XMLname, tab)


def EmitParameter(param, out, prefix=""):
  """Emit a Python property for a DeviceModel <parameter>
  """
  defvalue = "None"
  if hasattr(param.syntax.default, "value"):
    if param.syntax.boolean:
      defvalue = (param.syntax.default.value == "true")
    elif param.syntax.string:
      defvalue = '"' + param.syntax.default.value + '"'
    else:
      defvalue = param.syntax.default.value
  out.append("{0}self.p_{1} = {2}\n".format(prefix, param.name, defvalue))


def EmitClassForObj(obj, out):
  """Generate a class for a CWMP DeviceModel <object>.

  Args:
    obj - a generateDS object for a DeviceModel <object> node.
    out - list of strings to collect for output
  """
  out.append("class {0}:\n".format(XmlNameMangle(obj.name)))
  out.append("  def __init__(self):\n")

  if len(obj.parameter) > 0:
    out.append("    # <parameter> variables")
    for param in obj.parameter:
      EmitParameter(param, out, "    ")
    out.append("\n")
  else:
    out.append("    pass\n")

  out.append("\n")


def WhatToEmit(objects, emit_these):
  """Intersect objects with emit_these. If emit_these is empty, return all.

  Args:
    objects - list of object names
    emit_these - frozenset of object names to emit

  Returns:
    list of object names to emit
  """
  if emit_these:
    return [obj for obj in objects if obj in emit_these]
  else:
    return objects


def ParseDeviceModelFile(root, emit_these, out):
  """Parse an XML file, emitting Python classes for DeviceModel objects.

  The device model is defined in tr-106, which provides an XML schema to
  validate DeviceModel definition files.
  http://www.broadband-forum.org/cwmp/tr-106-1-2-0.xml
  The current schema (at the time of this writing) is:
  http://www.broadband-forum.org/cwmp/cwmp-datamodel-1-3.xsd

  The general XML format is:
  <document>
    <component>
      <object> - objects which can go at several top level models
    <model>
      <object> - objects specific to a model

  Args:
    root - the XML root node from the tr-106 compatible document
    emit_these - a frozenset of object names for which classes should be
      generated.  If None, _all_ objects will be generated.
    out - list of strings to collect for output
  """
  for model in root.model:
    for obj in WhatToEmit(model.object, emit_these):
      EmitClassForObj(obj, out)


def ParseCmdline():
  """Handle command line arguments.
  """
  optparser = optparse.OptionParser(
      description='Code generator for CWMP DataModel objects')
  optparser.add_option('--outfile', help="filename to write generated code to.")
  optparser.add_option('--dmfile', action='store',
      help="CWMP DeviceModel XML file to parse.",
      default='../schema/tr-181-2-0-1.xml')
  return optparser.parse_args()


def main():
  (options, args) = ParseCmdline()
  dm_objects = frozenset(args)
  out = []
  EmitPrologue(out)
  root = dm.parse(options.dmfile)
  ParseDeviceModelFile(root, dm_objects, out)

  outstr = "".join(out)
  if options.outfile:
    open(options.outfile, "w").write(outstr)
  else:
    print(outstr)

if __name__ == '__main__':
  main()
