#!/bin/sh

if [ -n $TESTOUTPUT ]; then
  echo $* >$TESTOUTPUT
fi

case "$1-$2" in
  cwmp-foo) exit 0 ;;
  cwmp-clear) exit 0 ;;
  bless-*) exit 0 ;;
  print-) echo -n 'bar'; exit 0 ;;
  *) exit 1 ;;
esac
