#!/bin/sh

if [ "$1" = "-r" ] && [ "$2" = "1ST_SERIAL_NUMBER" ]; then
  echo "1ST_SERIAL_NUMBER=123456789"
fi

if [ "$1" = "-r" ] && [ "$2" = "PLATFORM_NAME" ]; then
  echo "PLATFORM_NAME=ModelName"
fi

if [ "$1" = "-r" ] && [ "$2" = "GPN" ]; then
  echo "GPN=PartNumber"
fi

if [ "$1" = "-r" ] && [ "$2" = "HW_REV" ]; then
  echo "HW_REV=rev"
fi

exit 0
