#!/usr/bin/python
#
"""Command to start server in diagui.py."""

__author__ = 'anandkhare@google.com (Anand Khare)'

import diagui


# Listen for requests at port 8880
if __name__ == '__main__':
  inst = diagui.DiaguiSettings()
  inst.listen(8880)
  inst.ioloop.start()
