#!/bin/sh

if [ "$1" = "get" ] && [ "$2" = "wps_mfstring" ]; then
  echo "ASUSTeK Computer Inc."
fi

if [ "$1" = "get" ] && [ "$2" = "wps_modelnum" ]; then
  echo "RT-N16"
fi

if [ "$1" = "get" ] && [ "$2" = "hardware_version" ]; then
  echo "RT-N16-00-07-01-00"
fi

if [ "$1" = "get" ] && [ "$2" = "et0macaddr" ]; then
  echo "12:34:56:78:9A:BC"
fi

if [ "$1" = "get" ] && [ "$2" = "buildno" ]; then
  echo "20130102030405"
fi

exit 0
